pateik_app/urls.py
from django.template.defaulttags import url
from django.urls import path


from django.conf.urls.static import static
from django.views.static import serve

from pateik_app.views import *
from pateik_core import settings

urlpatterns = [
    path("", main_page, name="main-page"),
    path("profile/", Profile.as_view(), name="profile"),
    path("logout/", logout_view, name="logout"),
    path("registration/", CreateUser.as_view(), name="register-page"),
    path("about/", AboutPage.as_view(), name="about-page"),
    path("payment/<int:pk>/", payment_view, name="payment"),
    path("payment-success/", payment_success, name="payment-success"),
    path("payment-denied/", payment_denied, name="payment-denied"),
    path("ajax/load-times/", load_times, name="ajax_load_times"),
    path("login/", login_view, name="login-page"),
    path("webhook/", stripe_webhook),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "pateik"

pateik_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from pateik_core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pateik_app.urls", namespace="pateik")),
    path("accounts/", include("django.contrib.auth.urls")),
]

pateik_app/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


class Day(models.Model):
    date = models.DateField(default=datetime.now().strftime("%d %b, %Y"))

    def __str__(self):
        return self.date.strftime("%d %b, %Y")


class AvailableTime(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE,null=True)
    time_start = models.TimeField(null=True)

    def __str__(self):
        return self.time_start.strftime("%H:%M")



class TrainingPlan(models.Model):
    plan = models.CharField(max_length=15)
    price = models.PositiveIntegerField(default="20")

    def __str__(self):
        return self.plan


class Payment(models.Model):
    name = models.CharField(max_length=15, null=False)
    discord = models.CharField(max_length=30, null=False)
    day = models.ForeignKey(Day, on_delete=models.SET_NULL, null=True,related_name="training_day")
    time = models.ForeignKey(AvailableTime, on_delete=models.SET_NULL, null=True,related_name="training_time")
    price = models.ForeignKey(TrainingPlan, on_delete=models.CASCADE,related_name="training_price")


class Customer(AbstractUser):
    image = models.ImageField(upload_to="images/", default="pngwing.com.png")
    training_paid = models.ForeignKey(
        TrainingPlan,
        on_delete=models.CASCADE,
        related_name="customers",
        null=True,
        blank=True,
    )


class Training(models.Model):
    name = models.CharField(max_length=35)
    social = models.CharField(max_length=35)
    day_train = models.CharField(max_length=10)
    time_train = models.CharField(max_length=10)
    plan = models.ForeignKey(TrainingPlan, on_delete=models.CASCADE,related_name="training_plan")

    def __str__(self):
        return f"{self.name} {self.plan}"

templates/about.html
{% extends "base.html" %}
{% block content %}
			<!-- start banner Area -->
			<section class="about-banner">
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								About me
							</h1>	
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->	

			<!-- Start home-about Area -->
			<section class="home-about-area section-gap">
				<div class="container">
					<div class="row align-items-center justify-content-between">
						<div class="col-lg-6 col-md-6 home-about-left">
							<img style="border-radius: 20px" class="img-fluid" src="../static/img/Front_patrik.jpg" alt="">
						</div>
						<div class="col-lg-5 col-md-6 home-about-right">
							<h6>About</h6>
							<h1 class="text-uppercase">Biography</h1>
							<p>
                My name is Patrick Zakharchenko, since childhood I was fond of computer games and one day I discovered Fortnite.
                At first, I just played with friends, day by day I was addicted to the game with its amazing gameplay and that
                my level of play was getting higher every day. My esports career started with the Fortnite Summer Skirmish Tournament
                where I managed to win $34,000 for two. And very soon the Gambit Esports team became interested in me!
							</p>
{#							<a style="font-family: 'Open Sans SemiBold'" href="{% url "pateik:payment" pk=2 %}" class="primary-btn text-uppercase">Тренироваться</a>#}
						</div>
						<div class="col-lg-12 pt-60">
							<p>
                In the period from 2018-2020, I managed to win over $215,000, as well as play in such major tournaments as FNCS Season X, Australian Open 2020, Secret Skirmish and many others.							</p>
							<p>
                Now I'm a personal trainer! And I want to share my experience with people who want to start progressing faster in the game, and in the future - win tournaments!							</p>
						</div>
					</div>
          </div>
      </section>

			<!-- End home-about Area -->	

			<!-- Start timeline Area -->
			<section class="timeline pb-120">
            <div class="text-center">
                <div class="menu-content pb-70">
                    <div class="title text-center">
                        <h1 style="margin-top: 40px" class="mb-10">Achievements</h1>
                        <p>Here is a list of my biggest achievements</p>
                    </div>
                </div>
            </div>				
			  <ul>
			    <li>
			      <div class="content">
              <img style="width: 100px;height: 100px" class="img-fluid mx-auto d-block mb-30" src="../static/img/FNCS_SeasonX.png" alt="">
			        <h4>
			          <time>FNCS: Season X - Grand Finals: Europe</time>
			        </h4>
			        <p style="font-family: 'Open Sans SemiBold'"><b>Place:</b> 2</p>
			        <p style="font-family: 'Open Sans SemiBold'"><b>Result: </b>72 000$</p>
			      </div>
			    </li>
			    <li>
			      <div class="content">
			      	<img style="width: 100px;height: 100px;" class="img-fluid mx-auto d-block mb-30" src="../static/img/Fall_Skirmish_Series.webp" alt="">
			        <h4>
			          <time>Fortnite Fall Skirmish Series</time>
			        </h4>
              <p style="font-family: 'Open Sans SemiBold'"><b>Place:</b> 7</p>
			        <p style="font-family: 'Open Sans SemiBold'"><b>Result: </b>63,750$</p>
			      </div>
			    </li>
			    <li>
			      <div class="content">
              <img style="width: 100px;height: 100px;" class="img-fluid mx-auto d-block mb-30" src="../static/img/Secret%20skirmish.png" alt="">
			        <h4>
			          <time>Fortnite Secret Skirmish Series</time>
			        </h4>
              <p style="font-family: 'Open Sans SemiBold'"><b>Place:</b> 6</p>
			        <p style="font-family: 'Open Sans SemiBold'"><b>Result: </b>24,000$</p>
			      </div>
			    </li>
          <li>
			      <div class="content">
              <img style="width: 100px;height: 100px;" class="img-fluid mx-auto d-block mb-30" src="../static/img/fortnite-summer-skirmish-series.png" alt="">
			        <h4>
			          <time>Fortnite Summer Skirmish Series</time>
			        </h4>
              <p style="font-family: 'Open Sans SemiBold'"><b>Place:</b> 2</p>
			        <p style="font-family: 'Open Sans SemiBold'"><b>Result: </b>24,000$</p>
			      </div>
			    </li>

			  </ul>
			</section>		

			<!-- End timeline Area -->


			<!-- Start testimonial Area -->
{#		    <section class="testimonial-area section-gap">#}
{#		        <div class="container">#}
{#		            <div class="row d-flex justify-content-center">#}
{#		                <div class="menu-content pb-70 col-lg-8">#}
{#		                    <div class="title text-center">#}
{#		                        <h1 class="mb-10">Client’s Feedback About Me</h1>#}
{#		                        <p>It is very easy to start smoking but it is an uphill task to quit it. Ask any chain smoker or even a person.</p>#}
{#		                    </div>#}
{#		                </div>#}
{#		            </div>#}
{#		            <div class="row">#}
{#		                <div class="active-testimonial">#}
{#		                    <div class="single-testimonial item d-flex flex-row">#}
{#		                        <div class="thumb">#}
{#		                            <img class="img-fluid" src="../static/img/elements/user1.png" alt="">#}
{#		                        </div>#}
{#		                        <div class="desc">#}
{#		                            <p>#}
{#		                                Do you want to be even more successful? Learn to love learning and growth. The more effort you put into improving your skills, the bigger the payoff you.		     #}
{#		                            </p>#}
{#		                            <h4>Harriet Maxwell</h4>#}
{#		                            <p>CEO at Google</p>#}
{#		                        </div>#}
{#		                    </div>#}
{#		                    <div class="single-testimonial item d-flex flex-row">#}
{#		                        <div class="thumb">#}
{#		                            <img class="img-fluid" src="../static/img/elements/user2.png" alt="">#}
{#		                        </div>#}
{#		                        <div class="desc">#}
{#		                            <p>#}
{#		                                A purpose is the eternal condition for success. Every former smoker can tell you just how hard it is to stop smoking cigarettes. However.#}
{#		                            </p>#}
{#		                            <h4>Carolyn Craig</h4>#}
{#		                            <p>CEO at Facebook</p>#}
{#		                        </div>#}
{#		                    </div>#}
{#		                </div>#}
{#		            </div>#}
{#		        </div>#}
{#		    </section>#}
		    <!-- End testimonial Area -->			

		    <!-- Start brands Area -->
<section class="brands-area">
  <div class="container">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        <div class="col single-brand">
          <a href="#">
            <img style="width: 40px;height: 80px" class="mx-auto" src="/static/img/icons8-twitch.svg" alt="" />
          </a>
        </div>
        <div class="col single-brand">
          <a href="#">
            <img style="width: 40px;height: 80px" class="mx-auto" src="/static/img/icons8-ютуб%20(1).svg" alt="" />
          </a>
        </div>
        <div class="col single-brand">
          <a href="#">
            <img style="width: 40px;height: 80px" class="mx-auto" src="../static/img/icons8-твиттер.svg" alt="" />
          </a>
        </div>
        <div class="col single-brand">
          <a href="#">
            <img style="width: 40px;height: 80px" class="mx-auto" src="../static/img/icons8-instagram.svg" alt="" />
          </a>
        </div>
        <div class="col single-brand">
          <a href="#">
            <img style="width: 40px;height: 80px"  class="mx-auto" src="../static/img/icons8-телеграмма-app.svg" alt="" />
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
		    <!-- End brands Area -->

            <!-- End footer Area -->
        {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="anypay-verification" content="252e31583852126a3a8654cc4e39">
		<!-- Favicon-->
		<link rel="shortcut icon" href="/static/img/letter-p.png">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Pate1k -  Тренировки</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="/static/css/linearicons.css">
			<link rel="stylesheet" href="/static/css/font-awesome.min.css">
			<link rel="stylesheet" href="/static/css/bootstrap.css">
			<link rel="stylesheet" href="/static/css/magnific-popup.css">
			<link rel="stylesheet" href="/static/css/animate.min.css">
			<link rel="stylesheet" href="/static/css/owl.carousel.css">
    <link rel="stylesheet" href="/static/css/payment.css">
  <link rel="stylesheet" href="/static/js/main.js">
  <link rel="stylesheet" href="/static/css/linearicons.css">
  <link rel="stylesheet" href="/static/img/l5.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@500&display=swap" rel="stylesheet">

    {% block css %}
      <link href="{% static "css/payment.css" %}" rel="stylesheet" media="all">
      <link href="{% static "css/linearicons.css" %}" rel="stylesheet" media="all">

      <link href="{% static "css/main.css" %}" rel="stylesheet" media="all">

    {% endblock css %}
		</head>
		<body style="background: rgb(15,25,42);
background: linear-gradient(180deg, rgba(15,25,42,1) 0%, rgba(35,19,66,1) 33%, rgba(48,20,103,1) 72%, rgba(4,9,30,1) 100%);">
		  <header id="header">
		    <div class="container main-menu">
		    	<div class="row align-items-center justify-content-between d-flex">
			      <div id="logo">
			        <h4 style="color: black"><a href="{% url "pateik:main-page" %}">Pate1k</a></h4>
			      </div>
			      <nav id="nav-menu-container">
			        <ul class="nav-menu">
			          <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:main-page" %}">Home</a></li>
			          <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:about-page" %}">About</a></li>
                <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:payment" pk=2 %}">Training</a></li>

                {% if user.is_authenticated %}
                  <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:logout" %}">Logout</a></li>
                  <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:profile" %}">Profile</a></li>
                  {% else %}
                  <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:register-page" %}">Register</a></li>
                <li><a style="font-family: 'Noto Sans Display Medium',sans-serif;" href="{% url "pateik:login-page" %}">Login</a></li>
                {% endif %}
			        </ul>
			      </nav><!-- #nav-menu-container -->
		    	</div>
		    </div>
		  </header><!-- #header -->
      {% block content %}

      {% endblock %}



    	<script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
			<script src="/static/js/popper.min.js"></script>
			<script src="/static/js/vendor/bootstrap.min.js"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  		<script src="/static/js/easing.min.js"></script>
			<script src="/static/js/hoverIntent.js"></script>
			<script src="/static/js/superfish.min.js"></script>
			<script src="/static/js/jquery.ajaxchimp.min.js"></script>
			<script src="/static/js/jquery.magnific-popup.min.js"></script>
    	<script src="/static/js/jquery.tabs.min.js"></script>
			<script src="/static/js/jquery.nice-select.min.js"></script>
      <script src="/static/js/isotope.pkgd.min.js"></script>
			<script src="/static/js/waypoints.min.js"></script>
			<script src="/static/js/jquery.counterup.min.js"></script>
			<script src="/static/js/simple-skillbar.js"></script>
			<script src="/static/js/owl.carousel.min.js"></script>
			<script src="/static/js/mail-script.js"></script>
			<script src="/static/js/main.js"></script>
		</body>
	</html>

templates/drop_down_time.html
<option value="">Choose time</option>

{% for time in times %}
<option value="{{ time.pk }}">{{ time.time_start|date:"G:i" }}</option>
{% endfor %}

templates/payment-denied.html
{% extends "base.html" %} {% block content %}
<link rel="stylesheet" href="../static/css/payment-result.css" />
<section class="payment-result">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <div class="payment-result__content">
          <div class="payment-result__icon">
            <svg
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:cc="http://creativecommons.org/ns#"
              xmlns:dc="http://purl.org/dc/elements/1.1/"
              xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
            >
              <g transform="translate(0 -1028.4)">
                <path
                  d="m22 12c0 5.523-4.477 10-10 10-5.5228 0-10-4.477-10-10 0-5.5228 4.4772-10 10-10 5.523 0 10 4.4772 10 10z"
                  fill="#c0392b"
                  transform="translate(0 1029.4)"
                />
                <path
                  d="m22 12c0 5.523-4.477 10-10 10-5.5228 0-10-4.477-10-10 0-5.5228 4.4772-10 10-10 5.523 0 10 4.4772 10 10z"
                  fill="#e74c3c"
                  transform="translate(0 1028.4)"
                />
                <path
                  d="m7.0503 1037.8 3.5357 3.6-3.5357 3.5 1.4142 1.4 3.5355-3.5 3.536 3.5 1.414-1.4-3.536-3.5 3.536-3.6-1.414-1.4-3.536 3.5-3.5355-3.5-1.4142 1.4z"
                  fill="#c0392b"
                />
                <path
                  d="m7.0503 1036.8 3.5357 3.6-3.5357 3.5 1.4142 1.4 3.5355-3.5 3.536 3.5 1.414-1.4-3.536-3.5 3.536-3.6-1.414-1.4-3.536 3.5-3.5355-3.5-1.4142 1.4z"
                  fill="#ecf0f1"
                />
              </g>
            </svg>
          </div>
          <h2 class="payment-result__title">Payment denied...</h2>
          <p class="payment-result__text">An error occurred during payment...</p>
          <div class="payment-result__buttnons">
            <a href="{% url "pateik:main-page" %}" class="payment-result__btn primary-btn">Home</a>
            <a href="{% url "pateik:payment" pk=2 %}" class="btn btn--pill btn--green">Try again</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/payment-success.html
{% extends "base.html" %} {% block content %}
<link rel="stylesheet" href="../static/css/payment-result.css" />
<section class="payment-result">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <div class="payment-result__content">
          <div class="payment-result__icon">
            <svg
              id="Layer_1"
              style="enable-background: new 0 0 128 128;"
              version="1.1"
              viewBox="0 0 128 128"
              xml:space="preserve"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
            >
              <style type="text/css">
                .st0 {
                  fill: #31af91;
                }
                .st1 {
                  fill: #ffffff;
                }
              </style>
              <g><circle class="st0" cx="64" cy="64" r="64" /></g>
              <g>
                <path
                  class="st1"
                  d="M54.3,97.2L24.8,67.7c-0.4-0.4-0.4-1,0-1.4l8.5-8.5c0.4-0.4,1-0.4,1.4,0L55,78.1l38.2-38.2   c0.4-0.4,1-0.4,1.4,0l8.5,8.5c0.4,0.4,0.4,1,0,1.4L55.7,97.2C55.3,97.6,54.7,97.6,54.3,97.2z"
                />
              </g>
            </svg>
          </div>
          <h2 class="payment-result__title">Payment success</h2>
          <p class="payment-result__text">Our manager will contact you soon</p>
          <a href="{% url "pateik:main-page" %}" class="payment-result__btn primary-btn">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/payment_form.html
{% extends "base.html" %}
{% block content %}
			<!-- start banner Area -->
			<section class="about-banner">
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Start training!
							</h1>
              <h5 style="margin-top: 10px">
                Your plan {{ train.plan }} choose day and time!<br>
                For payment - {{ train.price }} $
              </h5>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start home-about Area -->
			<section class="home-about-area section-gap">
				<div class="container">
          <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading">
                  <ul class="slots-list"></ul>
                </div>
                <div class="card-body">
                    <h4 style="font-family: 'Open Sans SemiBold'">Choose start date!</h4>
                  <br>
                    <form method="POST" id="paymentForm" data-times-url="{% url 'pateik:ajax_load_times' %}" class="form">
                    {% csrf_token %}

 {#   -------------------USER NAME--------------------- #}
{#                        <div class="input-group" >#}
{#                              {{ form.name }}#}
{#                        </div>#}

{#   -------------------CHOSE DATE--------------------- #}

                        <div class="input-group" >
                                  {{ form.day }}
                              <div class="select-dropdown"></div>
                            </div>

{#   -------------------CHOSE TIME--------------------- #}

                        <div class="input-group">
                                {{ form.time }}
                              <div class="select-dropdown"></div>
                            </div>

{#   -------------------DISCORD--------------------- #}

                        <div class="input-group" >
                              {{ form.discord }}
                        </div>
                    {% if errors %}
                      {% for key,value in errors.items %}
                        <div class="alert alert-danger">
                          <strong>{{ value }}</strong>
                      </div>
                      {% endfor %}
                    {% endif %}

                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit" id="checkout-button">Payment</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        </div>
			</section>

			<!-- Start faq Area -->
      <div class="container mb-5">
        <div class="row justify-content-center">
          <div class="col-lg-8">
          <dl class="accordion">
            <dt>
              <a href="">
                Can I take a Duo partner?</a>
            </dt>
            <dd>

Yes, only if your tariff is Basic and above
            </dd>
            <dt>
              <a href="">I have chosen several workouts, when is the next one?</a>
            </dt>
            <dd>
If you choose Tariff Pro and above - only the first training is booked. The rest are planned individually with the trainer at the end of the first training session.            </dd>
            <dt>
              <a href="">What platform can you use?</a>
            </dt>
            <dd>
              Training can take place on any platform!
            </dd>
            <dt>
              <a href="">I don't have Discord, where will the communication be?</a>
            </dt>
            <dd>
              Communication during training will take place in the voice chat of the game or in Discord
            </dd>
            <dt>
              <a href="">
                Can I get a refund for training?</a>
            </dt>
            <dd>
It is impossible to return the funds, but we give a 100% guarantee that all workouts will be successfully completed
            </dd>
            <dt>
              <a href="">I accidentally entered incorrect contact information, what should I do?</a>
            </dt>
            <dd>
              If suddenly you have provided incorrect contact details - contact our support <a target="_blank" href="#">support</a> -
we will be happy to help you
            </dd>
          </dl>

          </div>
        </div>
      </div>
			<!-- End faq Area -->
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
              jQuery(document).ready(function($){
                $("#id_day").change(function () {
                  const url = $("#paymentForm").attr("data-times-url");
                  const dayId = $(this).val();
                $.ajax({
                    url: url,
                    data: {
                        'day': dayId
                    },
                    success: function (data) {
                        console.log(data)
                        $("#id_time").html(data);
                    }
                });
              });
            });
            </script>
  <script type="text/javascript">
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
      var checkoutButton = document.getElementById("checkout-button");
      checkoutButton.addEventListener("click", function () {
          fetch("{% url "pateik:payment" pk=train.pk %}", {
              method: "POST",
              headers: {
                  'X-CSRFToken': csrftoken
              }
          })
              .then(function (response) {
                  return response.json();
              })
              .then(function (session) {
                  return stripe.redirectToCheckout({sessionId: session.id});
              })
              .then(function (result) {
                  if (result.error) {
                      alert(result.error.message);
                  }
              })
              .catch(function (error) {
                  console.error("Error:", error);
              });
                      });
                  </script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
			<!-- start banner Area -->
			<section class="about-banner">
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Profile
							</h1>
              <h5 style="margin-top: 10px">
              </h5>
						</div>
					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start home-about Area -->
			<section class="home-about-area section-gap">
				<div class="container">
          <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div  style="background: url('{{ user.image.url }}')top left/cover no-repeat;;" class="card-profile-heading" >
                  <ul class="slots-list"></ul>
                </div>
                <div class="card-body">
                  <br>


 {#   -------------------USER NAME--------------------- #}
                              <h5>
                                <li>Your name : {{ user.username }}</li>
                                <li style="margin-bottom: 140px">{% if user.training_paid %}
                                  Training plan :{{ user.training_paid }}
                                  {% else %}
                                  You don`t have any trainings (
                                  {% endif %}
                                </li>
                              </h5>

                        {% if user.training_paid %}
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit" id="checkout-button"><a style="color: #FFFFFF" href=https://commerce-pwjx.onrender.com/#price-area">Update plan</a></button>
                        </div>
                          {% else %}
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit" id="checkout-button"><a style="color: #FFFFFF" href="https://commerce-pwjx.onrender.com/#price-area">Start!</a></button>
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
        </div>
			</section>

			<!-- Start faq Area -->

{% endblock %}